### ISSUE TITLE
Maven coordinate change in 1.3.0

### ISSUE THREAD

**Issue by hbmartin** [touchlab/SQLiter#115]
In the 1.3.0 release, it appears the Maven coords changed from `co.touchlab:sqliter-driver:$version` to `co.touchlab:sqliter:$version` (no driver)

Compare https://repo1.maven.org/maven2/co/touchlab/sqliter-driver/ and https://repo1.maven.org/maven2/co/touchlab/sqliter/

**Comment by kpgalligan** [comment]
Ah, you aren't wrong. The publishing code changed but I missed that part.

**Comment by kpgalligan** [comment]
On the way, although not synced to maven repo yet: https://github.com/touchlab/SQLiter/releases/tag/1.3.1

**Comment by hbmartin** [comment]
🙏 🎉
