### ISSUE TITLE
Use `sqlite3_close_v2` instead of `sqlite3_close`.

### ISSUE THREAD

**Issue by andersio** [touchlab/SQLiter#32]
`sqlite3_close_v2` marks connection as closed zombie, and internally defers deallocation of the connection as soon as all outstanding resources are finalized.

Switching to `sqlite3_close_v2` allows consumers of SQLiter to avoid extraneous resource tracking, as long as they are already closing/finalizing the resources properly (mainly active prepared statements).

An example scenario that will benefit from this is SQLDelight's NativeSqlDriver:

https://github.com/cashapp/sqldelight/blob/51e0621abe103761717d3d9078dcde3734ad8c04/drivers/native-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/native/NativeSqlDatabase.kt#L248-249

It might be a step towards not needing precise tracking of active statement objects, and in turn reducing the need on less performant shareable data structures in K/N.

> https://www.sqlite.org/c3ref/close.html
>
> The sqlite3_close_v2() interface is intended for use with host languages that are garbage collected, and where the order in which destructors are called is arbitrary.

**Comment by kpgalligan** [comment]
Added back in Jan. Closing.
