### ISSUE TITLE
K/N compiler crashes if you consume sqliter and also have a sqlite3 cinterop file with package = sqlite3

### ISSUE THREAD

**Issue by benasher44** [touchlab/SQLiter#45]
Our library also picked `package = sqlite3` for our sqlite cinterop, just sqliter did, which resulted in this hard-to-debug crash https://youtrack.jetbrains.com/issue/KT-46358.

package in this case defines the package used for the code K/N generates for interop'ing with that C. it should probably be name-spaced to the sqliter package: co.touchlab.sqliter

If you encounter this as a consumer, you can fix this yourself by fixing your cinterop's package name

**Comment by kpgalligan** [comment]
Fix in https://github.com/touchlab/SQLiter/releases/tag/v1.0.2
