### ISSUE TITLE
Test 1.7.20 beta

### ISSUE THREAD

**Issue by samhill303** [touchlab/SQLiter#76]

**Comment by russhwolf** [comment]
Sanity checks
1. Compile your project with a current Kotlin version.
1. Check the highlighting in different IDE modules.
1. Compile the project with the EAP Kotlin version and install the EAP IDE plugin.
1. Verify that the project re-imported successfully.
1. Check that highlighting from p.2 works not worse than before.
1. Compile the project again and look for new surprising warnings.
1. Change something in the code and check if incremental compilation works.
1. Run your tests with a new Kotlin version.
1. Stop at some well-known piece of code, run the debugger and try stepping.
1. Look for performance issues in compilation, runtime, re-import or IDE behavior.
